### PR TITLE
Seamless looping framework + times for Wild World

### PR DESCRIPTION
**Pull request by kowsen**
After some work, I have a framework for seamless looping of tracks, and have set up the loop times for Wild World. I haven't listened super closely to all the WW tracks, but for casual listening, I didn't hear any hiccups during the loops.

With this new setup, you can set start and end times for the loop in loopTimes.js. If no loop times exist for that game / hour combination, the extension will just loop the song from the beginning like it does currently. So right now if you listen to Wild World, you should get seamless loops for all hours, while the other games should function as they do in the current version.

Setting up loop times for the other games is super easy as far as the javascript is concerned, but time consuming to get the timecodes for the loop exactly right. I've added the loop points for 5pm in animal-forrest to show how to do this.

EDIT: I also added a debug flag in Utility.js, which prints some helpful text to the console and sets up some global functions to help with debugging when activated. If you're setting up loop times and want to check them without waiting for the correct time, make sure DEBUG_FLAG is true and that you're in the correct game, and then just call "setTime(hour)" in the web inspector console to change what hour the extension thinks it is.

NOTE: The method used for audio looping may not be compatible across different browsers, but for a chrome extension, that hopefully shouldn't matter too much. It's been rock-solid in every version of Chrome I've tested it in.

### CODE REVIEW

**Comment by JdotCarver** [comment]
Amazing! That's really great, but is there a way to play the intro only once. Like : play song from beginning if number of loops = 0 and from then on start the loop from x timestamp?

**Comment by kowsen** [comment]
That's actually how it works currently! The first time through it starts from the actual beginning of the song. The "start" timecode in loopTimes is just where the loop jumps back to each time it reaches "end".

**Comment by TheDirtySpaceman** [comment]
Haha you beat me to this I had a similar structure I was working on. I was having a bit of an issue with the listeners jumping around with the time stamps. How did you manage to get the html5 audio object to play nice? From what I understand the progress event listener only gives a new currentTime property every ~250ms and wasn't consistent in my testing. How do you trigger the loops?

Harold Houchin

**Comment by kowsen** [comment]
I tried the progress listener, but had the same issue you must have had - it wasn't precise enough. Instead, when the song starts and on each iteration of the loop, it sets a setTimeout - with a function that will change the audio object's currentTime to the start of the loop section of the song - to fire when we reach the end of the looping part of the song. This gives as little responsibility as possible to the html5 audio object, because you can't really trust it to be precise.

setTimeout isn't the most accurate timer in the world, but it's almost never off by more than 5-10 ms, which if you place your loop points well is nearly impossible to hear.

You can see the main part of this logic at AudioManager.js:37

**Comment by TheDirtySpaceman** [comment]
Nice work around! Very clever. Glad I wasn't crazy to try to use the
progress listener haha

**Comment by kowsen** [comment]
Thanks! If I've learned anything about JS, it's that you should try as hard as you can not to use setTimeout to hack your way around problems, but if you use them well you can work your way around pretty much anything.

**Comment by JdotCarver** [comment]
Man I so want to get working on it now! :D

**Comment by JdotCarver** [comment]
Could you please give me the name under which you'd like to appear in the credits? :)

**Comment by TheDirtySpaceman** [comment]
You can call me by my actual name or my username whatever matches everyone else :)

Harold Houchin or hh4hooch

Sorry I didn't get a chance to contribute more.

I was working on the loops and was beat to the punch.

**Comment by kowsen** [comment]
I'd like to be credited as Kyle Owsen.

Thanks!

**Pull request merged**
