### PR TITLE
Options page styling and alternate icons

### PR DESCRIPTION
**Pull request by mherndon6**
This is all up to date with GammaGames's pull request, so most of the changes below are from him. I've added some styling to the options page to make it look more like Animal Crossing, and I'm open to suggestions about the logo/design.

As for the icon, I added a darker leaf and made it an option to choose between kk and the leaf, which is what I think the original feature request was about. If we keep the option to choose icons and still want the icon to change when the user toggles music, we should implement it for both icons. For now, I commented out the lines in BadgeManager that change to the play/pause leaf. Personally, I think it's enough to have the badge text toggle on and off but let me know what you all think.

### CODE REVIEW

**Comment by mherndon6** [comment]
By the way, this seems kind of silly to have all of Gamma's changes in my request. If there's some way to do this that makes my own changes more clear, please let me know. I'm still pretty clueless with git.

**Comment by JdotCarver** [comment]
Unfortunately merging GammaGames' commit did create conflicts, I had thought merging them in order would actually prevent such a thing from happening.

On a side note some little feedback:
The hanging down sign on the Animal Crossing Logo is a nice addition but I'm not particularly digging the white font. My Initial logo design is in no way final, but consistency is pretty important when you're dealing with UX. _On that note having people design a new logo and then let the users vote for the designs they like best and then deliberate which one fits best would be a good idea don't you think?_
And secondly, an easy fix that I can do myself if you want. Don't forget that icons are on a transparent backgroud by nature, this changes their default alignment guidelines, you have your play and pause signs aligned to the center of the canvas but not the leaf they are actually supposed to rest on. So even though they are aligned in relation to the canvas they aren't in relation to each other.

**Comment by mherndon6** [comment]
The more recent changes must have made conflicts. I'm pretty busy with classes this week but I can fix the issues probably next weekend. 

Normally I'd agree with you about the white font, but I took the idea straight from the Wild World cover art (https://upload.wikimedia.org/wikipedia/en/6/64/Animal_Crossing_Wild_World_Game_Cover.jpg). I thought the consistency with the series was nice, and it might just be me but using the same orange color looks kind of off for some reason (http://imgur.com/4aMIQRs). With that said, a vote is a good idea. I'd just like to see some more color in the interface for the next update.

As for the icon, do you mean the icon_128_leaf-01 and icon_128_leaf-02? Those were in Gamma's original pull request. I think I disabled them and added the darker leaf for the same reasons you said, but his latest commits got rid of them anyway.

**Comment by JdotCarver** [comment]
I was talking about the logo's consistency as it already is all over the extension's page. But yeah you're right, orange does look a bit off... 
At least it pushes me to get this logo sorted out. Alright then, that I didn't notice!
On Jan 31, 2016 10:06 PM, Mitch Herndon notifications@github.com wrote:The more recent changes must have made conflicts. I'm pretty busy with classes this week but I can fix the issues probably next weekend. 

Normally I'd agree with you about the white font, but I took the idea straight from the Wild World cover art (https://upload.wikimedia.org/wikipedia/en/6/64/Animal_Crossing_Wild_World_Game_Cover.jpg). I thought the consistency with the series was nice, and it might just be me but using the same orange color looks kind of off for some reason (http://imgur.com/4aMIQRs). With that said, a vote is a good idea. I'd just like to see some more color in the interface for the next update.

As for the icon, do you mean the icon_128_leaf-01 and icon_128_leaf-02? Those were in Gamma's original pull request. I think I disabled them and added the darker leaf for the same reasons you said, but his latest commits got rid of them anyway.

**Comment by mherndon6** [comment]
Oh, gotcha. Next time I work on this I'll fix the conflicts and add yours for a temporary logo until we get around to a vote for a new logo.

**Comment by JdotCarver** [comment]
animal crossing music logo
And here's the temporary logo.

**Comment by paladique** [comment]
Gonna close this, as this is an old PR

**Pull request closed without merging**
