### PR TITLE
Fixed random mode

### PR DESCRIPTION
**Pull request by usersaurus**

### CODE REVIEW

**Comment by JdotCarver** [comment]
Hah great thanks, I'll just need to check it out again when I can then. :)

**Comment by JdotCarver** [comment]
Hmm Unfortunately it works, a bit. It randoms music, then you play pause and sometimes it will do whats its supposed to, sometimes it will play the same one again (have you thought of excluding the one being played atm from the random pool?) and sometimes it just won't play anything. Maybe pointing to an invalid path or invalid pointer?

**Comment by kowsen** [comment]
You need to remove 'new-leaf-live' from the list of options that random mode pulls from. It's trying to pull music from the 'new-leaf-live' folder, when no such folder exists.

**Comment by kowsen** [comment]
I fixed the bug, as well as another bug I found in my pull request - #17

**Comment by usersaurus** [comment]
Ye, i saw that (other) bug yesterday, but i had no time at all to fix it D:

**Pull request merged**
