### PR TITLE
Random mode added (finally!).

### PR DESCRIPTION
**Pull request by usersaurus**

### CODE REVIEW

**Comment by JdotCarver** [comment]
Hah, I see you like your values properly aligned. Good work alromangit. Shall I credit you with that username?

**Comment by JdotCarver** [comment]
Is it supposed to pick a random song after each play or after a certain time?

**Comment by usersaurus** [comment]
It's supposed to pick a random song every time u select "random" and every hour. I tested it and it works :P

**Comment by usersaurus** [comment]
And if it 's not too much trouble, use my real name in credits: Antonio Luis Román.

**Comment by usersaurus** [comment]
Ok, I found a bug. I will fix it today.

**Comment by usersaurus** [comment]
Fixed!

**Pull request merged**
